// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: chain.proto

package chainpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChainQuery_Ping_FullMethodName           = "/chainpb.ChainQuery/Ping"
	ChainQuery_GetLatestBlock_FullMethodName = "/chainpb.ChainQuery/GetLatestBlock"
)

// ChainQueryClient is the client API for ChainQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChainQuery 演示：HTTP(Gin) 与 gRPC 可并行对外暴露同一后端数据源。
type ChainQueryClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetLatestBlock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlockSummary, error)
}

type chainQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewChainQueryClient(cc grpc.ClientConnInterface) ChainQueryClient {
	return &chainQueryClient{cc}
}

func (c *chainQueryClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ChainQuery_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainQueryClient) GetLatestBlock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlockSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockSummary)
	err := c.cc.Invoke(ctx, ChainQuery_GetLatestBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainQueryServer is the server API for ChainQuery service.
// All implementations must embed UnimplementedChainQueryServer
// for forward compatibility.
//
// ChainQuery 演示：HTTP(Gin) 与 gRPC 可并行对外暴露同一后端数据源。
type ChainQueryServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	GetLatestBlock(context.Context, *Empty) (*BlockSummary, error)
	mustEmbedUnimplementedChainQueryServer()
}

// UnimplementedChainQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainQueryServer struct{}

func (UnimplementedChainQueryServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedChainQueryServer) GetLatestBlock(context.Context, *Empty) (*BlockSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (UnimplementedChainQueryServer) mustEmbedUnimplementedChainQueryServer() {}
func (UnimplementedChainQueryServer) testEmbeddedByValue()                    {}

// UnsafeChainQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainQueryServer will
// result in compilation errors.
type UnsafeChainQueryServer interface {
	mustEmbedUnimplementedChainQueryServer()
}

func RegisterChainQueryServer(s grpc.ServiceRegistrar, srv ChainQueryServer) {
	// If the following call panics, it indicates UnimplementedChainQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainQuery_ServiceDesc, srv)
}

func _ChainQuery_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainQuery_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainQuery_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainQueryServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainQuery_GetLatestBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainQueryServer).GetLatestBlock(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainQuery_ServiceDesc is the grpc.ServiceDesc for ChainQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainpb.ChainQuery",
	HandlerType: (*ChainQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ChainQuery_Ping_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _ChainQuery_GetLatestBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chain.proto",
}
