// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: web3.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EthTxService_GetTransaction_FullMethodName        = "/web3.EthTxService/GetTransaction"
	EthTxService_GetTransactionReceipt_FullMethodName = "/web3.EthTxService/GetTransactionReceipt"
	EthTxService_SubscribeTransactions_FullMethodName = "/web3.EthTxService/SubscribeTransactions"
	EthTxService_SubscribeLogs_FullMethodName         = "/web3.EthTxService/SubscribeLogs"
	EthTxService_CreateAccount_FullMethodName         = "/web3.EthTxService/CreateAccount"
	EthTxService_GetAccount_FullMethodName            = "/web3.EthTxService/GetAccount"
	EthTxService_Transfer_FullMethodName              = "/web3.EthTxService/Transfer"
	EthTxService_CreateUser_FullMethodName            = "/web3.EthTxService/CreateUser"
	EthTxService_GetUser_FullMethodName               = "/web3.EthTxService/GetUser"
	EthTxService_BindUserAccount_FullMethodName       = "/web3.EthTxService/BindUserAccount"
	EthTxService_ListUserAccounts_FullMethodName      = "/web3.EthTxService/ListUserAccounts"
)

// EthTxServiceClient is the client API for EthTxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EthTxServiceClient interface {
	GetTransaction(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*EthTransaction, error)
	GetTransactionReceipt(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*TxReceipt, error)
	SubscribeTransactions(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EthTransaction], error)
	SubscribeLogs(ctx context.Context, in *SubscribeLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	BindUserAccount(ctx context.Context, in *BindUserAccountRequest, opts ...grpc.CallOption) (*BindUserAccountResponse, error)
	ListUserAccounts(ctx context.Context, in *ListUserAccountsRequest, opts ...grpc.CallOption) (*ListUserAccountsResponse, error)
}

type ethTxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEthTxServiceClient(cc grpc.ClientConnInterface) EthTxServiceClient {
	return &ethTxServiceClient{cc}
}

func (c *ethTxServiceClient) GetTransaction(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*EthTransaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EthTransaction)
	err := c.cc.Invoke(ctx, EthTxService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) GetTransactionReceipt(ctx context.Context, in *TxHashRequest, opts ...grpc.CallOption) (*TxReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxReceipt)
	err := c.cc.Invoke(ctx, EthTxService_GetTransactionReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) SubscribeTransactions(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EthTransaction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EthTxService_ServiceDesc.Streams[0], EthTxService_SubscribeTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, EthTransaction]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EthTxService_SubscribeTransactionsClient = grpc.ServerStreamingClient[EthTransaction]

func (c *ethTxServiceClient) SubscribeLogs(ctx context.Context, in *SubscribeLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EthTxService_ServiceDesc.Streams[1], EthTxService_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeLogsRequest, LogEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EthTxService_SubscribeLogsClient = grpc.ServerStreamingClient[LogEvent]

func (c *ethTxServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, EthTxService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, EthTxService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, EthTxService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, EthTxService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, EthTxService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) BindUserAccount(ctx context.Context, in *BindUserAccountRequest, opts ...grpc.CallOption) (*BindUserAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindUserAccountResponse)
	err := c.cc.Invoke(ctx, EthTxService_BindUserAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTxServiceClient) ListUserAccounts(ctx context.Context, in *ListUserAccountsRequest, opts ...grpc.CallOption) (*ListUserAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserAccountsResponse)
	err := c.cc.Invoke(ctx, EthTxService_ListUserAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthTxServiceServer is the server API for EthTxService service.
// All implementations must embed UnimplementedEthTxServiceServer
// for forward compatibility.
type EthTxServiceServer interface {
	GetTransaction(context.Context, *TxHashRequest) (*EthTransaction, error)
	GetTransactionReceipt(context.Context, *TxHashRequest) (*TxReceipt, error)
	SubscribeTransactions(*SubscribeRequest, grpc.ServerStreamingServer[EthTransaction]) error
	SubscribeLogs(*SubscribeLogsRequest, grpc.ServerStreamingServer[LogEvent]) error
	CreateAccount(context.Context, *CreateAccountRequest) (*Account, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	BindUserAccount(context.Context, *BindUserAccountRequest) (*BindUserAccountResponse, error)
	ListUserAccounts(context.Context, *ListUserAccountsRequest) (*ListUserAccountsResponse, error)
	mustEmbedUnimplementedEthTxServiceServer()
}

// UnimplementedEthTxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEthTxServiceServer struct{}

func (UnimplementedEthTxServiceServer) GetTransaction(context.Context, *TxHashRequest) (*EthTransaction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedEthTxServiceServer) GetTransactionReceipt(context.Context, *TxHashRequest) (*TxReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionReceipt not implemented")
}
func (UnimplementedEthTxServiceServer) SubscribeTransactions(*SubscribeRequest, grpc.ServerStreamingServer[EthTransaction]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTransactions not implemented")
}
func (UnimplementedEthTxServiceServer) SubscribeLogs(*SubscribeLogsRequest, grpc.ServerStreamingServer[LogEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedEthTxServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedEthTxServiceServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedEthTxServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedEthTxServiceServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedEthTxServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedEthTxServiceServer) BindUserAccount(context.Context, *BindUserAccountRequest) (*BindUserAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindUserAccount not implemented")
}
func (UnimplementedEthTxServiceServer) ListUserAccounts(context.Context, *ListUserAccountsRequest) (*ListUserAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserAccounts not implemented")
}
func (UnimplementedEthTxServiceServer) mustEmbedUnimplementedEthTxServiceServer() {}
func (UnimplementedEthTxServiceServer) testEmbeddedByValue()                      {}

// UnsafeEthTxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EthTxServiceServer will
// result in compilation errors.
type UnsafeEthTxServiceServer interface {
	mustEmbedUnimplementedEthTxServiceServer()
}

func RegisterEthTxServiceServer(s grpc.ServiceRegistrar, srv EthTxServiceServer) {
	// If the following call panics, it indicates UnimplementedEthTxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EthTxService_ServiceDesc, srv)
}

func _EthTxService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).GetTransaction(ctx, req.(*TxHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_GetTransactionReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).GetTransactionReceipt(ctx, req.(*TxHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_SubscribeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EthTxServiceServer).SubscribeTransactions(m, &grpc.GenericServerStream[SubscribeRequest, EthTransaction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EthTxService_SubscribeTransactionsServer = grpc.ServerStreamingServer[EthTransaction]

func _EthTxService_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EthTxServiceServer).SubscribeLogs(m, &grpc.GenericServerStream[SubscribeLogsRequest, LogEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EthTxService_SubscribeLogsServer = grpc.ServerStreamingServer[LogEvent]

func _EthTxService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_BindUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).BindUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_BindUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).BindUserAccount(ctx, req.(*BindUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTxService_ListUserAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTxServiceServer).ListUserAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EthTxService_ListUserAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTxServiceServer).ListUserAccounts(ctx, req.(*ListUserAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EthTxService_ServiceDesc is the grpc.ServiceDesc for EthTxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EthTxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web3.EthTxService",
	HandlerType: (*EthTxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransaction",
			Handler:    _EthTxService_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _EthTxService_GetTransactionReceipt_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _EthTxService_CreateAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _EthTxService_GetAccount_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _EthTxService_Transfer_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _EthTxService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _EthTxService_GetUser_Handler,
		},
		{
			MethodName: "BindUserAccount",
			Handler:    _EthTxService_BindUserAccount_Handler,
		},
		{
			MethodName: "ListUserAccounts",
			Handler:    _EthTxService_ListUserAccounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTransactions",
			Handler:       _EthTxService_SubscribeTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _EthTxService_SubscribeLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "web3.proto",
}
